"""add_progress_tables

Revision ID: c48ef6ba999d
Revises: 3a8b39a14193
Create Date: 2024-06-02 11:03:17.070003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48ef6ba999d'
down_revision: Union[str, None] = '3a8b39a14193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_ask_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_ask_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_ask_contents_id'), 'progress_ask_contents', ['id'], unique=False)
    op.create_table('progress_ask_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_ask_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_ask_roles_id'), 'progress_ask_roles', ['id'], unique=False)
    op.create_table('progress_asks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('ask_message_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_asks_id'), 'progress_asks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_asks_id'), table_name='progress_asks')
    op.drop_table('progress_asks')
    op.drop_index(op.f('ix_progress_ask_roles_id'), table_name='progress_ask_roles')
    op.drop_table('progress_ask_roles')
    op.drop_index(op.f('ix_progress_ask_contents_id'), table_name='progress_ask_contents')
    op.drop_table('progress_ask_contents')
    # ### end Alembic commands ###
