"""fix_fk

Revision ID: 61cd58709387
Revises: 38cafa5eafd1
Create Date: 2024-06-02 12:15:42.262629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cd58709387'
down_revision: Union[str, None] = '38cafa5eafd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_ask_contents', sa.Column('progress_ask_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'progress_ask_contents', 'progress_asks', ['progress_ask_id'], ['id'])
    op.add_column('progress_ask_roles', sa.Column('progress_ask_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'progress_ask_roles', 'progress_asks', ['progress_ask_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress_ask_roles', type_='foreignkey')
    op.drop_column('progress_ask_roles', 'progress_ask_id')
    op.drop_constraint(None, 'progress_ask_contents', type_='foreignkey')
    op.drop_column('progress_ask_contents', 'progress_ask_id')
    # ### end Alembic commands ###
